"""update models in database

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-24 11:40:50.238681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat_participants', ['user_id'])
    op.add_column('chats', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'])
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited_at')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'owner_id')
    op.drop_constraint(None, 'chat_participants', type_='unique')
    # ### end Alembic commands ###
