"""update chat table

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-26 19:06:28.845587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_avatar_url', sa.String(), nullable=True))
    op.drop_column('chats', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'chat_avatar_url')
    # ### end Alembic commands ###
